current/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$', include('movies.urls', namespace="movies")),
	url(r'^admin/', include(admin.site.urls)),
]

movies/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

movies/models.py
from django.db import models

# Create your models here.

class Films(models.Model):
	title = models.CharField(max_length=100, blank=False)
	release_year = models.IntegerField(blank=True)
	locations = models.CharField(max_length=200, blank=True)
	fun_facts = models.CharField(max_length=500, blank=True)
	production_company = models.CharField(max_length=200, blank=True)
	distributor = models.CharField(max_length=200, blank=True)
	director = models.CharField(max_length=100, blank=True)
	writer = models.CharField(max_length=100, blank=True)
	actor_1 = models.CharField(max_length=100, blank=True)
	actor_2 = models.CharField(max_length=100, blank=True)
	actor_3 = models.CharField(max_length=100, blank=True)
	latitude = models.FloatField()
	longitude = models.FloatField()
	
	def __str__(self):              # __unicode__ on Python 2
		return self.title

movies/forms.py
from django.forms import ModelForm, TextInput
from movies.models import Films

class FilmsForm(ModelForm):
	
	class Meta:
		model = Films
		#fields = ['title', 'release_year', 'director', 'actor_1']
		fields = ['title']
		widgets = {
			'title': TextInput(attrs={'required': True, 'id': 'mytitle'}),
		}

movies/views.py
import urllib, urllib.request, json, csv, os
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.db.models import Q, Count

from .forms import FilmsForm
from .models import Films

# Create your views here.

def index(request):
	
	all_entries = Films.objects.all()
	if len(all_entries) == 0:		# database is empty
		filename = 'sfmovies.csv'
		csv_filepathname = settings.MEDIA_ROOT + filename
		dataReader = csv.reader(open(csv_filepathname, encoding='utf-8'), delimiter=',', quotechar='"')
		for row in dataReader:
			if row[0] != 'Title':		# Ignore the header row, import everything else
				films = Films()
				films.title = row[0]
				films.release_year = int(row[1])
				films.locations = row[2]
				films.fun_facts = row[3]
				films.production_company = row[4]
				films.distributor = row[5]
				films.director = row[6]
				films.writer = row[7]
				films.actor_1 = row[8]
				films.actor_2 = row[9]
				films.actor_3 = row[10]
				films.latitude = 0
				films.longitude = 0
				films.save()

	if request.is_ajax():
		q = request.GET.get('term', '')
		film_list = Films.objects.filter(title__icontains=q)
		title_list = film_list.values('title').annotate(total=Count('title'))
		results = []
		for film in title_list:
			results.append(film['title'])
		data = json.dumps(results)
		mimetype = 'application/json'
		return HttpResponse(data, mimetype)
	
	# if this is a POST request we need to process the form data
	elif request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = FilmsForm(request.POST)
		# check whether it's valid:
		if form.is_valid():
			# process the data in form.cleaned_data as required
			# ...
			# redirect to a new URL:
			film_list = Films.objects.filter(title__icontains=request.POST['title'])
			
			if len(film_list) == 0:		# no records in database for given query
				form = FilmsForm()
				return render(request, 'movies/index.html', {
					'error_message': "No records found. Search for something else.",
					'form': form,
					'film_list': film_list,
				})
			
			else:
				title_list = film_list.values('title').annotate(total=Count('title'))
				title_len = len(title_list)
				title_string = request.POST['title']
				context_list = []
				
				for a in title_list:
					temp_list = film_list.filter(title__iexact=a['title'])
					a_dict = {}
					a_dict['title'] = temp_list[0].title
					a_dict['release_year'] = temp_list[0].release_year
					a_dict['production_company'] = temp_list[0].production_company
					a_dict['distributor'] = temp_list[0].distributor
					a_dict['director'] = temp_list[0].director
					a_dict['writer'] = temp_list[0].writer
					a_dict['actor_1'] = temp_list[0].actor_1
					a_dict['actor_2'] = temp_list[0].actor_2
					a_dict['actor_3'] = temp_list[0].actor_3
					location_list = []
				
					for film in temp_list:
						if film.locations:	# if location is available
							if film.latitude == 0:		# no coordinates in database
								address = film.locations + ', San Francisco, CA'
								address = address.replace(" ", "+")
								key = '&key=AIzaSyCj1SDXgNgYPk11mBJEAMeX3tJpSOKJn_M'
								url = "https://maps.googleapis.com/maps/api/geocode/json?address=%s" % address
								url += key
								try:
									response = urllib.request.urlopen(url).read().decode("utf-8")
								except:
									smile = ':)'
								else:
									result = json.loads(response)
									if result['status'] == 'OK':
										lat = float(str(result['results'][0]['geometry']['location']['lat']))
										lng = float(str(result['results'][0]['geometry']['location']['lng']))
										film.latitude = lat
										film.longitude = lng
										film.save()
										
							# end if
							loc_dict = {}
							loc_dict['loc'] = film.locations
							loc_dict['lat'] = film.latitude
							loc_dict['lng'] = film.longitude
							location_list.append(loc_dict)
							
					# end for
					a_dict['locations'] = location_list
					context_list.append(a_dict)

				# end for
				context = {
					'film_list' : context_list,
					'title_len' : title_len,
					'title_string' : title_string,
				}
				return render(request, 'movies/result.html', context)

	# if a GET (or any other method) we'll create a blank form
	else:
		film_list = Films.objects.filter(~Q(latitude=0))
		form = FilmsForm()
		return render(request, 'movies/index.html', {'form': form, 'film_list': film_list})

	return render(request, 'movies/index.html', {'form': form})

movies/templates/movies/index.html
<!DOCTYPE html>
<html>
	<head>
	<title>SF Movies</title>
		<style type="text/css">
			html, body { height: 100%; margin: 0; padding: 0; }
			#map { height: 100%; }
		</style>
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
		
		<script>
		$(function() {
			$("#mytitle").autocomplete({
				source: "",
				minLength: 1,
			});
		});
		</script>
		
	</head>
	
	<body>
	<div style="float:left; width:40%; overflow: auto;">
	<form action="{% url 'movies:index' %}" method="post">

	
	<ul>
	<script type="text/javascript">
	


	
	var label = [];
	var temp = [];
	</script>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	{% csrf_token %}
	{{ form.as_p }}
	{% for film in film_list %}
		{% if  film.locations %}
			<script type="text/javascript">
			temp = []
			temp.push('{{ film.title }}');
			temp.push('{{ film.release_year }}');
			temp.push('{{ film.locations }}');
			temp.push({{ film.latitude }});
			temp.push({{ film.longitude }});
			label.push(temp);
			</script>
		{% endif %}
	{% endfor %}
	</ul>
	<input type="submit" value="Submit" />
	</form>
	</div>

	<div id="map" style="float:left; width: 60%; height: 100%"></div>
	<script type="text/javascript">

		var map;
		function initMap() {
			map = new google.maps.Map(document.getElementById('map'), {
				center: {lat: 37.7521662, lng: -122.4474315},
				zoom: 11
			});
			
			var myLatLng;
			for (i = 0; i < label.length; ++i)
			{
				myLatLng = {lat: label[i][3], lng: label[i][4]};
				var contentString = '<h1 id="firstHeading" class="firstHeading">label[i][0]</h1>';
				var marker = new google.maps.Marker({
					position: myLatLng,
					map: map,
					title: label[i][0] + ' (' + label[i][1] + ') @ ' + label[i][2]
				});
			}

		}

	</script>
	<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCj1SDXgNgYPk11mBJEAMeX3tJpSOKJn_M&callback=initMap">
	</script>
	</body>
</html>

movies/templates/movies/result.html
<!DOCTYPE html>
<html>
	<head>
	<title>SF Movies Results</title>
		<style type="text/css">
			html, body { height: 100%; margin: 0; padding: 0; }
			#map { height: 100%; }
		</style>
	</head>
	
	<body>
	<div style="float:left; width:40%; overflow: auto;">
	<form action="{% url 'movies:index' %}" method="get">
	<ol>
	<script type="text/javascript">
	var label = [];
	var temp = [];
	</script>
	
	<h3> {{ title_len }} result(s) found for '{{ title_string }}' </h3>
	
	{% for film in film_list %}
	
		{% if film.title %}
		<li> Title: {{ film.title }}
		{% endif %}
		<ul>
		{% if film.release_year %}
		<li> Release Year: {{ film.release_year }} </li>
		{% endif %}
		{% if film.production_company %}	
		<li> Production Company: {{ film.production_company }} </li>
		{% endif %}
		{% if film.distributor %}
		<li> Distributor: {{ film.distributor }} </li>
		{% endif %}
		{% if film.director %}
		<li> Director: {{ film.director }} </li>
		{% endif %}
		{% if film.writer %}
		<li> Writer: {{ film.writer }} </li>
		{% endif %}
		{% if film.actor_1 %}
		<li> Actor(s):
			<ul>
			{% if film.actor_1 %}
			<li> {{ film.actor_1 }} </li>
			{% endif %}
			{% if film.actor_2 %}
			<li> {{ film.actor_2 }} </li>
			{% endif %}
			{% if film.actor_3 %}
			<li> {{ film.actor_3 }} </li>
			{% endif %}
			</ul>
		</li>
		{% endif %}
		<li> Location(s):
			<ul>
			{% for location in film.locations %}
				{% if location.loc %}
					<li> {{ location.loc }} </li>
						<script type="text/javascript">
						temp = []
						temp.push('{{ film.title }}');
						temp.push('{{ film.release_year }}');
						temp.push('{{ location.loc }}');
						temp.push({{ location.lat }});
						temp.push({{ location.lng }});
						label.push(temp);
						</script>
				{% endif %}
			{% endfor %}
			</ul>
		</li>
		</ul>
		</li>
		</br>
		</br>
	{% endfor %}
	</ol>
	<input type="submit" value="Try again" />
	</form>
	</div>

	<div id="map" style="float:left; width: 60%; height: 100%"></div>
	<script type="text/javascript">

		var map;
		function initMap() {
			map = new google.maps.Map(document.getElementById('map'), {
				center: {lat: 37.7521662, lng: -122.4474315},
				zoom: 11
			});
			
			var myLatLng;
			for (i = 0; i < label.length; ++i)
			{
				myLatLng = {lat: label[i][3], lng: label[i][4]};
				var contentString = '<h1 id="firstHeading" class="firstHeading">label[i][0]</h1>';
				var marker = new google.maps.Marker({
					position: myLatLng,
					map: map,
					title: label[i][0] + ' (' + label[i][1] + ') @ ' + label[i][2]
				});
			}

		}

	</script>
	<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCj1SDXgNgYPk11mBJEAMeX3tJpSOKJn_M&callback=initMap">
	</script>
	</body>
</html>